### ISSUE TITLE
Error: spawn npx ENOENT

### ISSUE THREAD

**Issue by martindonadiosap** [SAP/ctz#11]
In Win x64, I get the error below after running " ctz containerize.yaml "

**Error: spawn npx ENOENT**

The containerize.yaml file was generated by CDS DK with command cds add containerize

**Comment by Roncossek** [comment]
We run in the same error on our Windows machines

**Comment by marcsst** [comment]
![image](https://github.com/user-attachments/assets/8cf28232-0f36-4c5d-9b92-a03ed230be15)


> "Error: spawn npx ENOENT\n    at ChildProcess._handle.onexit (node:internal/child_process:286:19)\n    at onErrorNT (node:internal/child_process:484:16)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"

**Comment by martindonadiosap** [comment]
Hi @marcsst , didn't try that option. but adding '.cmd' in the main command (npx) also fixes the issue for me under windows.

**Comment by shubho5** [comment]
We will look into it. adding {shell: true} in the option should resolve the issue.

**Comment by shubho5** [comment]
It is released now. Please download the latest(0.2.4) version.
