### ISSUE TITLE
tags not respected during image build

### ISSUE THREAD

**Issue by sickmartian** [SAP/ctz#12]
In `processBuildpack` the `tag` parameter is not used: https://github.com/SAP/ctz/blob/3907ea8f8794371147995e4cc6f0ba4adb58104f/lib/parse_yaml.js#L37C51

So, if `containerize.yaml` has a `tag` property with a value other than `latest` it will still build `latest` but try to push something else, as the tag is respected properly in other places.

**Comment by robinkuck** [comment]
Hi @sickmartian, this bug was fixed in the last release (https://github.com/SAP/ctz/releases/tag/v0.2.3).
